In [1]:
import behaviors
import no_signaling_sets
import numpy as np
from tqdm import tqdm

In [2]:
delta=2
m=2

n_hyperplanes = -1

In [3]:
non_srns_samples = np.load("../data/non_srns/non_srns_points.npy")
# non_srns_samples = list(non_srns_samples)

example_sample = np.random.choice(len(non_srns_samples), 1)[0]
example_sample = non_srns_samples[example_sample]
example_sample = behaviors.RoutedBehavior(delta, m, vector=example_sample)

srns_set = no_signaling_sets.ShortRangeNoSignalingSet(delta, m)

print(f"Example sample: {example_sample}")
print(f"Example sample is no-signaling: [{example_sample.is_no_signaling()}]")

np.linalg.matrix_rank(np.array(non_srns_samples))

Example sample: Behavior:
Short path (z=S):
[[0.2348075  0.19389147 0.48537691 0.42544478]
 [0.37186253 0.41277856 0.09661883 0.15655096]
 [0.32120358 0.25696171 0.07063417 0.02540839]
 [0.0721264  0.13636827 0.34737009 0.39259587]]
Long path (z=L) :
[[0.57622529 0.42205417 0.48446445 0.57323496]
 [0.03044474 0.18461585 0.09753129 0.00876078]
 [0.02803147 0.19417754 0.11979231 0.04299676]
 [0.3652985  0.19915244 0.29821195 0.37500751]]
------------
Example sample is no-signaling: [True]


np.int64(15)

In [4]:
# print(f"Hyperplane: {srns_set.get_facet_hyperplane(example_sample)}")

In [5]:
def normalize_vector(vector):
    norm = np.linalg.norm(vector)
    if norm == 0:
        return vector
    return vector / norm

all_hyperplanes = set()

In [6]:
for vec in tqdm(list(non_srns_samples)[:n_hyperplanes]):
    _, _, vec_lambda = srns_set.is_facet_hyperplane(
        behaviors.RoutedBehavior(delta, m, vec)
        )
    all_hyperplanes.add(str(normalize_vector(vec_lambda)))

100%|██████████| 2700778/2700778 [1:39:41<00:00, 451.49it/s]


In [7]:
print(f"Number of hyperplanes: {len(all_hyperplanes)}")

# copy_hyperplanes = all_hyperplanes.copy()
# while copy_hyperplanes:
#     hyperplane = copy_hyperplanes.pop()
#     print(hyperplane)
#     print("\n\n")

Number of hyperplanes: 32
