In [22]:
import behaviors
import no_signaling_sets
import numpy as np
from tqdm import tqdm

In [23]:
delta=2
m=2

n_hyperplanes = int(1e5)

In [24]:
non_srns_samples = np.load("../data/non_srns/non_srns_points.npy")
# non_srns_samples = list(non_srns_samples)

example_sample = np.random.choice(len(non_srns_samples), 1)[0]
example_sample = non_srns_samples[example_sample]
example_sample = behaviors.RoutedBehavior(delta, m, vector=example_sample)

srns_set = no_signaling_sets.ShortRangeNoSignalingSet(delta, m)

print(f"Example sample: {example_sample}")
print(f"Example sample is no-signaling: [{example_sample.is_no_signaling()}]")

np.linalg.matrix_rank(np.array(non_srns_samples))

Example sample: Behavior:
Short path (z=S):
[[0.22051509 0.09267573 0.37241    0.3746263 ]
 [0.08432102 0.21216038 0.06596184 0.06374554]
 [0.60307359 0.38161634 0.45117869 0.09966577]
 [0.09209029 0.31354755 0.11044948 0.46196239]]
Long path (z=L) :
[[0.29493571 0.24756012 0.20136944 0.28246687]
 [0.00990041 0.057276   0.23700239 0.15590497]
 [0.04586153 0.05515545 0.1394278  0.0202487 ]
 [0.64930235 0.64000843 0.42220036 0.54137947]]
------------
Example sample is no-signaling: [True]


np.int64(15)

In [25]:
family = non_srns_samples[:n_hyperplanes]
family_rank = np.linalg.matrix_rank(family)
print(f"Rank of family: {family_rank}")

chosen_hyperplane = srns_set.get_facet_hyperplane(example_sample)
hyperplane_behavior = behaviors.RoutedBehavior(delta, m, vector=chosen_hyperplane)

print(f"Hyperplane: {chosen_hyperplane}")
print(f"In behavior expression: {hyperplane_behavior}")

2025-05-23 17:10:58.862 | WARNING  | no_signaling_sets:get_facet_hyperplane:386 - The has rank 11, not yet identified as maximal hyperplane dimension.


Rank of family: 15
Hyperplane: [ 0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          1.93782839  0.         -1.93782839  1.93782839
  1.93782839  0.          0.          0.          1.93782839 -1.93782839
  0.          0.        ]
In behavior expression: Behavior:
Short path (z=S):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Long path (z=L) :
[[ 0.          0.          0.          0.        ]
 [ 1.93782839  0.         -1.93782839  1.93782839]
 [ 1.93782839  0.          0.          0.        ]
 [ 1.93782839 -1.93782839  0.          0.        ]]
------------


In [26]:
def normalize_vector(vector):
    norm = np.linalg.norm(vector)
    if norm == 0:
        return vector
    return vector / norm

all_hyperplanes = set()

In [27]:
# for vec in tqdm(list(non_srns_samples)[:n_hyperplanes]):
#     _, _, vec_lambda = srns_set.is_facet_hyperplane(
#         behaviors.RoutedBehavior(delta, m, vec)
#         )
#     all_hyperplanes.add(str(normalize_vector(vec_lambda)))

In [28]:
print(f"Number of hyperplanes: {len(all_hyperplanes)}")

copy_hyperplanes = all_hyperplanes.copy()
while copy_hyperplanes:
    hyperplane = copy_hyperplanes.pop()
    print(hyperplane)
    print("\n\n")

Number of hyperplanes: 0
