## Imports

In [56]:
import behaviors
import no_signaling_sets
import numpy as np
import samplers

In [57]:
delta = 2
m = 2

sampler = samplers.NoSignalingSampler(delta, m)
srns_set = no_signaling_sets.ShortRangeNoSignalingSet(delta, m)

## Run once

In [58]:
sampled_behavior = sampler.sample()

result = srns_set.lp_test(sampled_behavior)

print(f"alpha value: {-result.fun}")

2025-05-20 11:25:19.165 | SUCCESS  | samplers:sample_multiple:100 - Samples shape: (1, 32)
2025-05-20 11:25:19.166 | DEBUG    | no_signaling_sets:express_as_function_of_q:194 - Estimated memory complexity of lacking_betas: 56 bytes


alpha value: 0.9296472646009349


## Check the closest SRNS behavior

In [59]:
yielded_behavior = behaviors.LatentSRNSBehavior(
    delta=delta,
    m=m,
    vector=np.clip(np.array(result.x[1:]), 0, 1),
)

print(f"Yielded behavior is {yielded_behavior}")
print(f"Yielded behavior is tested [{yielded_behavior.is_no_signaling()}] to being no signaling")


Yielded behavior is Behavior:
Short path (z=S):
[[0.35324638 0.42660973 0.25469169 0.27870084]
 [0.10402075 0.0306574  0.22746521 0.20345606]
 [0.19703528 0.02820924 0.29558997 0.17611813]
 [0.34569758 0.51452363 0.22225313 0.34172497]]
Long path (z=L) :
[[0.26338844 0.21931217]
 [0.09282112 0.        ]
 [0.10105757 0.20844031]
 [0.         0.05440442]
 [0.         0.04407628]
 [0.28776775 0.38058886]
 [0.10738274 0.        ]
 [0.14758238 0.09317796]]
------------
Yielded behavior is tested [True] to being no signaling


## Sanity check

In [60]:
print(f"PR box is tested [{srns_set.is_in_set(behaviors.pr_box)}] to being SRNS")


2025-05-20 11:25:19.182 | DEBUG    | no_signaling_sets:express_as_function_of_q:194 - Estimated memory complexity of lacking_betas: 56 bytes


PR box is tested [False] to being SRNS
